
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

notifications:
  email: false
node_js:
  - '10'
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential
  - cd Beta && npm i
script:
  - npm test
services: mongodb